version: '3'
services:
  # https://hub.docker.com/_/postgres?tab=description
  postgres:
    image: postgres:13.0
    user: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chat-compo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    # https://stackoverrun.com/ja/q/9534403
    logging:
      driver: none # console log none
    environment:
       PGADMIN_DEFAULT_EMAIL: naokisyuu@gmail.com
       PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgres
